name: Build Windows Unpackaged Release

on:
  push:
    branches: [ release ]

env:
    DOTNETVERSION: 8.0.201
    CONFIGURATION: Release # Values: Debug, Release
    PLATFORM: Any CPU # Values: x64, Any CPU
    VERSIONNUMBER: 1.${{ github.run_number }}.${{ github.run_attempt }}
    
jobs:
  buildWindowsPackaged:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '${{env.DOTNETVERSION}}'

      - name: List installed .NET info
        shell: pwsh
        run: dotnet --info

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - uses: managedcode/MAUIAppVersion@v1
        with:
          csproj: 'MauiBlazorHybridApp2.csproj'
          version: 0 # Revision number must be 0 on Windows to be allowed on MS Store https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/package-version-numbering?pivots=store-installer-msix#version-numbering-for-windows10-packages
          displayVersion: '${{ env.VERSIONNUMBER }}'
          printFile: true # optional

      # https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview
      - name: Build Windows EXE
        run: |
          cd .\
          dotnet publish -f net8.0-windows10.0.19041.0 -c:${{ env.CONFIGURATION }} -p:AppxPackageSigningEnabled=false -p:WindowsPackageType=None --self-contained

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-windows
          path: |
            .\bin\${{ env.PLATFORM }}\${{ env.CONFIGURATION }}\net8.0-windows10.0.19041.0\win10-x64\publish\**\*
